Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
Y_actual = pd.Series([0,0,1,0,0,1,0], name = 'actual')
Y_predict = pd.Series([0,0,1,1,0,0,1], name = 'predict')

pd.crosstab(Y_actual, Y_predict)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_19760/2034558955.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mY_actual[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mSeries[0m[1;33m([0m[1;33m[[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m,[0m [0mname[0m [1;33m=[0m [1;34m'actual'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mY_predict[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mSeries[0m[1;33m([0m[1;33m[[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m1[0m[1;33m][0m[1;33m,[0m [0mname[0m [1;33m=[0m [1;34m'predict'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [0mpd[0m[1;33m.[0m[0mcrosstab[0m[1;33m([0m[0mY_actual[0m[1;33m,[0m [0mY_predict[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

